AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  CobblerImageService:
    Type: AWS::Serverless::Api
    Description: "Serverless API for Cobbler images"
    Properties:
      Name: "cobbler-image-service"
      StageName: Prod
      Auth:
        DefaultAuthorizer: AWS_IAM
        InvokeRole: NONE  
      Cors:
        AllowMethods: "'OPTIONS, POST, DELETE'"
        AllowHeaders: "'Content-Type, x-amz-content-sha256, x-amz-date, X-Amz-Security-Token, Authorization'"
        # AllowOrigin: "'http://localhost:5173'"
        AllowOrigin: "'https://cobbler.phil-code.com'"
        AllowCredentials: true

      # Logging settings
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: "/*"
          HttpMethod: "*"
          MetricsEnabled: true
          DataTraceEnabled: true
      AccessLogSetting:
        DestinationArn: 
          Fn::GetAtt:
            - CobblerImageLogGroup
            - Arn
        Format: '$context.identity.sourceIp $context.identity.caller $context.identity.user [$context.requestTime] "$context.httpMethod $context.resourcePath $context.protocol" $context.status $context.responseLength $context.requestId'

  CobblerImageLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/api-gateway/${CobblerImageService}"
      RetentionInDays: 7    

  CobblerImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: bootstrap
      Runtime: provided.al2023
      MemorySize: 512
      Policies:
        - AWSLambdaExecute
        - PolicyName: S3DeletePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:DeleteObject
                Resource:
                  - !Sub arn:aws:s3:::${ImageBucketName}/assets/*

      Events:
        ImageOptions:
          Type: Api
          Properties:
            Path: /image
            Method: OPTIONS
            RestApiId: !Ref CobblerImageService
            Auth:
              Authorizer: NONE
        ImageOptionsId:
          Type: Api
          Properties:
            Path: /image/{id}
            Method: OPTIONS
            RestApiId: !Ref CobblerImageService
            Auth:
              Authorizer: NONE
        PutImage:
          Type: Api
          Properties:
            Path: /image
            Method: POST
            RestApiId: !Ref CobblerImageService
        DeleteImage:
          Type: Api
          Properties:
            Path: /image/{id}
            Method: DELETE
            RestApiId: !Ref CobblerImageService
    Metadata:
      BuildMethod: makefile
