AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ApiKeyValue:
    Type: String
    NoEcho: true
    Description: "API Key for the CobblerImageService"

Resources:
  CobblerImageService:
    Type: AWS::Serverless::Api
    Description: "Serverless API for Cobbler images"
    Properties:
      Name: "cobbler-image-service"
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS, POST, DELETE'"
        AllowHeaders: "'Content-Type, x-api-key'"
        # AllowOrigin: "'http://localhost:5173'"
        AllowOrigin: "'https://cobbler.phil-code.com'"
      Auth:
        ApiKeyRequired: true

  CobblerImageApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn: CobblerImageServiceProdStage
    Properties:
      Name: "CobblerImageApiKey"
      Enabled: true
      Value: !Ref ApiKeyValue
      StageKeys:
        - RestApiId: !Ref CobblerImageService
          StageName: Prod

  CobblerImageUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: CobblerImageServiceProdStage
    Properties:
      UsagePlanName: "CobblerImageUsagePlan"
      ApiStages:
        - ApiId: !Ref CobblerImageService
          Stage: Prod
      Throttle:
        RateLimit: 100
        BurstLimit: 20
      Quota:
        Limit: 10000
        Period: MONTH

  CobblerImageUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref CobblerImageApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref CobblerImageUsagePlan

  CobblerImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: bootstrap
      Runtime: provided.al2023
      MemorySize: 512
      Policies:
        - AWSLambdaExecute
      Events:
        ImageOptions:
          Type: Api
          Properties:
            Path: /image
            Method: OPTIONS
            RestApiId: !Ref CobblerImageService
            Auth:
              ApiKeyRequired: false
        PutImage:
          Type: Api
          Properties:
            Path: /image
            Method: POST
            RestApiId: !Ref CobblerImageService
            Auth:
              ApiKeyRequired: true
        DeleteImage:
          Type: Api
          Properties:
            Path: /image/{id}
            Method: DELETE
            RestApiId: !Ref CobblerImageService
            Auth:
              ApiKeyRequired: true
    Metadata:
      BuildMethod: makefile
